-- הריצי ב-Supabase SQL Editor

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default 'לקוחה',
  review_text text not null,
  stars integer not null default 5 check (stars >= 1 and stars <= 5),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists reviews_status_created_idx
  on public.reviews (status, created_at desc);

alter table public.reviews enable row level security;

drop policy if exists "Public read approved reviews" on public.reviews;
create policy "Public read approved reviews"
  on public.reviews
  for select
  using (status = 'approved');
