-- הריצי את כל הקובץ הזה ב-Supabase SQL Editor (פעם אחת)

-- === upgrade-v2: שדות שמלה + טבלת bookings ===
alter table public.dresses add column if not exists city text not null default '';
alter table public.dresses add column if not exists color text not null default '';
alter table public.dresses add column if not exists event_type text not null default '';
alter table public.dresses add column if not exists owner_name text not null default '';
alter table public.dresses add column if not exists owner_phone text not null default '';
-- === site_users: התחברות לאתר ===
create table if not exists public.site_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  display_name text not null default '',
  phone text not null default '',
  email text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists site_users_username_idx on public.site_users (username);

alter table public.dresses add column if not exists owner_email text not null default '';
alter table public.dresses add column if not exists deposit numeric not null default 0 check (deposit >= 0);
alter table public.dresses add column if not exists pickup_method text not null default 'pickup';

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  dress_id bigint not null references public.dresses(id) on delete cascade,
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  event_date date not null,
  status text not null default 'confirmed',
  created_at timestamptz not null default now()
);

create unique index if not exists bookings_dress_date_unique
  on public.bookings (dress_id, event_date)
  where status = 'confirmed';

create index if not exists bookings_dress_idx on public.bookings (dress_id, event_date);
alter table public.bookings enable row level security;

-- === upgrade-v3: דירוגים, תשלום, מחיקה ===
alter table public.dresses drop constraint if exists dresses_status_check;
alter table public.dresses add constraint dresses_status_check
  check (status in ('pending', 'approved', 'rejected', 'removed'));

alter table public.dresses add column if not exists rental_count integer not null default 0 check (rental_count >= 0);
alter table public.dresses add column if not exists rating_sum integer not null default 0 check (rating_sum >= 0);
alter table public.dresses add column if not exists rating_count integer not null default 0 check (rating_count >= 0);

create table if not exists public.dress_ratings (
  id bigint generated by default as identity primary key,
  dress_id bigint not null references public.dresses(id) on delete cascade,
  customer_name text not null,
  stars integer not null check (stars between 1 and 5),
  review_text text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists dress_ratings_dress_idx on public.dress_ratings (dress_id, created_at desc);
alter table public.dress_ratings enable row level security;
drop policy if exists "Public read dress ratings" on public.dress_ratings;
create policy "Public read dress ratings" on public.dress_ratings for select using (true);

alter table public.bookings add column if not exists amount_total numeric;
alter table public.bookings add column if not exists platform_fee numeric;
alter table public.bookings add column if not exists owner_payout numeric;
alter table public.bookings add column if not exists tranzila_index text;
alter table public.bookings add column if not exists payment_confirmed_at timestamptz;
alter table public.bookings add column if not exists site_user_id uuid;

alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check
  check (status in ('pending_payment', 'confirmed', 'cancelled', 'failed'));

-- === upgrade-v4: אישור תשלום ידני (ביט / העברה בנקאית) ===
alter table public.bookings add column if not exists payment_method text;
alter table public.bookings add column if not exists payment_reported_at timestamptz;

alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check
  check (status in ('pending_payment', 'awaiting_admin_approval', 'confirmed', 'cancelled', 'failed'));

-- === upgrade-v5: אישור דירוגי שמלות ===
alter table public.dress_ratings add column if not exists status text;
update public.dress_ratings set status = 'approved' where status is null;
alter table public.dress_ratings alter column status set default 'pending';
alter table public.dress_ratings alter column status set not null;
alter table public.dress_ratings drop constraint if exists dress_ratings_status_check;
alter table public.dress_ratings add constraint dress_ratings_status_check
  check (status in ('pending', 'approved'));

-- ניקוי יבש כלול במחיר
alter table public.dresses add column if not exists includes_dry_cleaning boolean not null default false;
