-- הריצי ב-Supabase SQL Editor (אחרי upgrade-v2.sql)

-- סטטוס "הוסרה" לשמלות
alter table public.dresses drop constraint if exists dresses_status_check;
alter table public.dresses add constraint dresses_status_check
  check (status in ('pending', 'approved', 'rejected', 'removed'));

-- דירוגים ומספר השכרות לכל שמלה
alter table public.dresses add column if not exists rental_count integer not null default 0 check (rental_count >= 0);
alter table public.dresses add column if not exists rating_sum integer not null default 0 check (rating_sum >= 0);
alter table public.dresses add column if not exists rating_count integer not null default 0 check (rating_count >= 0);

-- דירוגים לשמלה ספציפית (מפורסמים מיד)
create table if not exists public.dress_ratings (
  id bigint generated by default as identity primary key,
  dress_id bigint not null references public.dresses(id) on delete cascade,
  customer_name text not null,
  stars integer not null check (stars between 1 and 5),
  review_text text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists dress_ratings_dress_idx on public.dress_ratings (dress_id, created_at desc);

alter table public.dress_ratings enable row level security;

drop policy if exists "Public read dress ratings" on public.dress_ratings;
create policy "Public read dress ratings"
  on public.dress_ratings for select using (true);

-- שדות תשלום בשריונות
alter table public.bookings add column if not exists amount_total numeric;
alter table public.bookings add column if not exists platform_fee numeric;
alter table public.bookings add column if not exists owner_payout numeric;
alter table public.bookings add column if not exists tranzila_index text;
alter table public.bookings add column if not exists payment_confirmed_at timestamptz;

alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check
  check (status in ('pending_payment', 'confirmed', 'cancelled', 'failed'));
