-- הריצי ב-Supabase SQL Editor

alter table public.dresses add column if not exists city text not null default '';
alter table public.dresses add column if not exists color text not null default '';
alter table public.dresses add column if not exists event_type text not null default '';
alter table public.dresses add column if not exists owner_name text not null default '';
alter table public.dresses add column if not exists owner_phone text not null default '';
alter table public.dresses add column if not exists deposit numeric not null default 0 check (deposit >= 0);
alter table public.dresses add column if not exists pickup_method text not null default 'pickup';

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  dress_id bigint not null references public.dresses(id) on delete cascade,
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  event_date date not null,
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now()
);

create unique index if not exists bookings_dress_date_unique
  on public.bookings (dress_id, event_date)
  where status = 'confirmed';

create index if not exists bookings_dress_idx on public.bookings (dress_id, event_date);

alter table public.bookings enable row level security;
