'use client';

import React, { useState, useEffect } from 'react';

// נתוני השמלות המורחבים (התחלתיים) [cite: 248]
const INITIAL_DRESSES = [
  { 
    id: 1, 
    name: "שמלת ערב קלאסית קורל", 
    price: 350, 
    size: "M", 
    condition: "like-new",
    images: [
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1539008835657-9e8e818128e5?w=600&auto=format&fit=crop&q=80"
    ], 
    description: "שמלת ערב נשפכת בגוון קורל יוקרתי, מתאימה לחתונה או אירוע ערב חגיגי. בד נעים ומחטב." [cite: 248]
  }, [cite: 249]
  { 
    id: 2, 
    name: "שמלת סאטן אמרלד", 
    price: 420, 
    size: "S", 
    condition: "new",
    images: [
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1518049360962-53651b57c0e8?w=600&auto=format&fit=crop&q=80"
    ], 
    description: "שמלת סאטן מבריקה בגזרת מקסי בצבע ירוק אמרלד עמוק. שסע עדין ברגל ומחשוף קלאסי." [cite: 249]
  }, [cite: 250]
  { 
    id: 3, 
    name: "שמלת נשף נפוחה שחורה", 
    price: 550, 
    size: "L", 
    condition: "used",
    images: [
      "https://images.unsplash.com/photo-1518049360962-53651b57c0e8?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&auto=format&fit=crop&q=80"
    ], 
    description: "שמלת נשף דרמטית לחובבות המראה האצילי. חלקה העליון מחוך תומך וחלקה התחתון עשיר בטול." [cite: 250]
  } [cite: 251]
];

const FAQS = [
  { q: "האם המחיר כולל ניקוי יבש?", a: "בטח! כל השמלות עוברות ניקוי יבש מקצועי קפדני לפני ואחרי כל השכרה. את מקבלת את השמלה מוכנה ללבישה ומחזירה אותה ככה, אנחנו דואגים להכל." [cite: 251] },
  { q: "איך מתבצע תהליך המדידות וההתאמה?", a: "לאחר שריון השמלה באתר, אנחנו נתאם איתך הגעה לסטודיו חגיגי למדידות. במידת הצורך נבצע מכפלת או התאמות קלות שלא פוגעות בגזרת השמלה המקורית." [cite: 252] },
  { q: "מהי מדיניות הביטולים שלכן?", a: "ביטול שריון חינם יתאפשר עד 14 ימים לפני מועד האירוע המתוכנן. בביטול מאוחר יותר ייגבו דמי רצינות בגובה 15% מעלות ההשכרה." [cite: 253] },
  { q: "האם נדרש להשאיר פיקדון?", a: "כן, במעמד לקחת השמלה מהסטודיו נבקש להשאיר כרטיס אשראי לביטחון בלבד. לא מבוצע שום חיוב אלא אם נגרם נזק בלתי הפיך לשמלה." [cite: 254] }
];

const REVIEWS = [
  { name: "מיכל אהרוני", role: "כלה", text: "השכרתי את שמלת האמרלד לחתונה של אחותי ולא הפסקתי לקבל מחמאות כל הערב! הבד ישב פשוט מושלם והשירות בסטודיו היה של נסיכות.", stars: 5 }, [cite: 255]
  { name: "דניאל לוי", role: "מלווה", text: "חוויה מדהימה! השמלה הגיעה נקייה ומגוהצת כמו חדשה מהניילון. מערכת השריון באתר חסכה לי המון כאב ראש.", stars: 5 },
  { name: "שירז כהן", role: "אירוע חברה", text: "הצלתן אותי בדקה ה-90. השמלה ישבה בדיוק לפי המידות והרגשתי כמו על השטיח האדום. מומלץ בחום!", stars: 5 }
];

export default function Home() { [cite: 256]
  // רשימת שמלות דינמית
  const [dressesList, setDressesList] = useState(INITIAL_DRESSES); [cite: 256]

  // פילטרים [cite: 257]
  const [searchTerm, setSearchTerm] = useState(''); [cite: 257]
  const [maxPrice, setMaxPrice] = useState(600); [cite: 257]
  const [selectedSize, setSelectedSize] = useState('All'); [cite: 257]
  const [showOnlyFavorites, setShowOnlyFavorites] = useState(false); [cite: 258]

  // מועדפים וסל (שמירה ב-State) [cite: 258]
  const [favorites, setFavorites] = useState<number[]>([]); [cite: 258]
  const [cart, setCart] = useState<typeof INITIAL_DRESSES>([]); [cite: 259]
  const [isCartOpen, setIsCartOpen] = useState(false); [cite: 259]

  // מודאל הוספת שמלה חדשה [cite: 260]
  const [isAddDressOpen, setIsAddDressOpen] = useState(false); [cite: 260]
  const [newDressData, setNewDressData] = useState({ [cite: 261]
    name: '',
    price: '',
    size: '',
    color: '',
    condition: 'new',
    description: '',
    images: [] as string[]
  }); [cite: 261]

  // תאריכים תפוסים (מניעת כפל הזמנות - סימולציה) [cite: 262]
  const [bookedDates, setBookedDates] = useState<{ [dressId: number]: string[] }>({ [cite: 262]
    1: ['2026-07-15', '2026-08-01'], [cite: 262]
    2: ['2026-07-20'], [cite: 262]
    3: [] [cite: 262]
  }); [cite: 262]

  // מודאלים ושריון [cite: 263]
  const [selectedDress, setSelectedDress] = useState<typeof INITIAL_DRESSES[0] | null>(null); [cite: 263]
  const [orderName, setOrderName] = useState(''); [cite: 263]
  const [orderPhone, setOrderPhone] = useState(''); [cite: 264]
  const [orderEmail, setOrderEmail] = useState(''); [cite: 264]
  const [orderDate, setOrderDate] = useState(''); [cite: 264]
  const [isOrdered, setIsOrdered] = useState(false); [cite: 264]
  const [dateError, setDateError] = useState(''); [cite: 265]

  // אינדקס גלריה לכל כרטיס [cite: 265]
  const [currentImageIndexes, setCurrentImageIndexes] = useState<{ [key: number]: number }>({ [cite: 265]
    1: 0, 2: 0, 3: 0 [cite: 265]
  }); [cite: 265]
  const [modalImageIndex, setModalImageIndex] = useState(0); [cite: 266]

  // אקורדיון FAQ פעיל [cite: 266]
  const [activeFaq, setActiveFaq] = useState<number | null>(null); [cite: 266]

  // טעינת מועדפים מהדפדפן [cite: 267]
  useEffect(() => { [cite: 267]
    const savedFavs = localStorage.getItem('luxe_favs'); [cite: 267]
    if (savedFavs) setFavorites(JSON.parse(savedFavs)); [cite: 267]
    const savedCart = localStorage.getItem('luxe_cart'); [cite: 267]
    if (savedCart) setCart(JSON.parse(savedCart)); [cite: 267]
  }, []); [cite: 267]

  const toggleFavorite = (id: number, e: React.MouseEvent) => { [cite: 268]
    e.stopPropagation(); [cite: 268]
    let updated; [cite: 268]
    if (favorites.includes(id)) { [cite: 269]
      updated = favorites.filter(favId => favId !== id); [cite: 269]
    } else { [cite: 270]
      updated = [...favorites, id]; [cite: 270]
    } [cite: 270]
    setFavorites(updated); [cite: 270]
    localStorage.setItem('luxe_favs', JSON.stringify(updated)); [cite: 270]
  }; [cite: 270]

  const toggleCart = (dress: typeof INITIAL_DRESSES[0], e: React.MouseEvent) => { [cite: 271]
    e.stopPropagation(); [cite: 271]
    let updated; [cite: 271]
    if (cart.some(item => item.id === dress.id)) { [cite: 272]
      updated = cart.filter(item => item.id !== dress.id); [cite: 272]
    } else { [cite: 273]
      updated = [...cart, dress]; [cite: 273]
    } [cite: 273]
    setCart(updated); [cite: 273]
    localStorage.setItem('luxe_cart', JSON.stringify(updated)); [cite: 273]
  }; [cite: 273]

  const nextImage = (dressId: number, maxImages: number, e: React.MouseEvent) => { [cite: 274]
    e.stopPropagation(); [cite: 274]
    setCurrentImageIndexes(prev => ({ ...prev, [dressId]: (prev[dressId] + 1) % maxImages })); [cite: 275]
  }; [cite: 275]

  const prevImage = (dressId: number, maxImages: number, e: React.MouseEvent) => { [cite: 276]
    e.stopPropagation(); [cite: 276]
    setCurrentImageIndexes(prev => ({ ...prev, [dressId]: (prev[dressId] - 1 + maxImages) % maxImages })); [cite: 277]
  }; [cite: 277]

  const checkDateAvailability = (date: string, dressId: number) => { [cite: 278]
    if (bookedDates[dressId]?.includes(date)) { [cite: 278]
      return false; [cite: 278]
    } [cite: 279]
    return true; [cite: 279]
  }; [cite: 279]

  const handleDateChange = (date: string) => { [cite: 279]
    setOrderDate(date); [cite: 279]
    if (selectedDress && !checkDateAvailability(date, selectedDress.id)) { [cite: 280]
      setDateError('אופס! השמלה כבר תפוסה בתאריך זה. אנא בחרי תאריך אחר או דגם חלופי.'); [cite: 280]
    } else { [cite: 281]
      setDateError(''); [cite: 281]
    } [cite: 281]
  }; [cite: 281]

  const handlePlaceOrder = async (e: React.FormEvent) => { [cite: 282]
    e.preventDefault(); [cite: 282]
    if (!orderName || !orderPhone || !orderEmail || !orderDate || !selectedDress) return; [cite: 283]
    if (!checkDateAvailability(orderDate, selectedDress.id)) return; [cite: 283]
    try { [cite: 284]
      const response = await fetch('/api/send-sms', { [cite: 284]
        method: 'POST', [cite: 284]
        headers: { 'Content-Type': 'application/json' }, [cite: 284]
        body: JSON.stringify({ [cite: 284]
          name: orderName, [cite: 284]
          phone: orderPhone, [cite: 284]
          email: orderEmail, [cite: 284]
          dressName: selectedDress.name, [cite: 284]
          date: orderDate [cite: 284]
        }), [cite: 285]
      }); [cite: 284]

      const data = await response.json(); [cite: 285]
      if (data.success) { [cite: 286]
        setBookedDates(prev => ({ [cite: 286]
          ...prev, [cite: 286]
          [selectedDress.id]: [...(prev[selectedDress.id] || []), orderDate] [cite: 286]
        })); [cite: 286]
        setIsOrdered(true); [cite: 287]
        setTimeout(() => { [cite: 287]
          setIsOrdered(false); [cite: 287]
          setSelectedDress(null); [cite: 287]
          setOrderName(''); [cite: 287]
          setOrderPhone(''); [cite: 287]
          setOrderEmail(''); [cite: 287]
          setOrderDate(''); [cite: 287]
        }, 4000); [cite: 287]
      } else { [cite: 288]
        alert('הייתה בעיה ברישום ההזמנה במערכת'); [cite: 288]
      } [cite: 288]
    } catch (error) { [cite: 289]
      console.error('Error:', error); [cite: 289]
      alert('תקלה בתקשורת עם השרת'); [cite: 289]
    } [cite: 289]
  }; [cite: 289]

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => { [cite: 290]
    if (e.target.files) { [cite: 290]
      const filesArray = Array.from(e.target.files); [cite: 290]
      const urlsArray = filesArray.map(file => URL.createObjectURL(file)); [cite: 291]
      setNewDressData(prev => ({ [cite: 291]
        ...prev, [cite: 291]
        images: [...prev.images, ...urlsArray] [cite: 291]
      })); [cite: 291]
    } [cite: 292]
  }; [cite: 292]

  const handleAddDressSubmit = (e: React.FormEvent) => { [cite: 292]
    e.preventDefault(); [cite: 292]
    if (!newDressData.name || !newDressData.price || !newDressData.size) { [cite: 293]
      alert('אנא מלאי שדות חובה (שם, מחיר ומידה)'); [cite: 293]
      return; [cite: 293]
    } [cite: 294]

    const newDress = { [cite: 294]
      id: Date.now(), [cite: 294]
      name: newDressData.name, [cite: 294]
      price: Number(newDressData.price), [cite: 294]
      size: newDressData.size, [cite: 294]
      condition: newDressData.condition, [cite: 294]
      images: newDressData.images.length > 0 ? [cite: 294]
        newDressData.images : ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&auto=format&fit=crop&q=80"], [cite: 295]
      description: `${newDressData.description || 'אין תיאור זמין.'} | צבע: ${newDressData.color || 'לא צוין'} | מצב: ${ [cite: 295, 296]
        newDressData.condition === 'new' ? [cite: 297]
          'חדש עם תווית' : newDressData.condition === 'like-new' ? 'כמו חדש' : 'יד שנייה' [cite: 297]
      }` [cite: 297]
    }; [cite: 297]
    setDressesList(prev => [newDress, ...prev]); [cite: 298]
    setIsAddDressOpen(false); [cite: 298]
    setNewDressData({ name: '', price: '', size: '', color: '', condition: 'new', description: '', images: [] }); [cite: 298]
    alert('השמלה התווספה בהצלחה לקולקציה באתר!'); [cite: 299]
  }; [cite: 299]

  const filteredDresses = dressesList.filter(dress => { [cite: 300]
    const matchesSearch = dress.name.toLowerCase().includes(searchTerm.toLowerCase()); [cite: 300]
    const matchesPrice = dress.price <= maxPrice; [cite: 300]
    const matchesSize = selectedSize === 'All' || dress.size === selectedSize; [cite: 300]
    const matchesFav = !showOnlyFavorites || favorites.includes(dress.id); [cite: 300]
    return matchesSearch && matchesPrice && matchesSize && matchesFav; [cite: 300]
  }); [cite: 300]

  return ( [cite: 301]
    <main className="min-h-screen bg-gradient-to-b from-[#fbf8f0] via-[#f3ebd6] to-[#e8dcbd] text-[#332c1e] pb-24 relative overflow-hidden" dir="rtl"> [cite: 301]
      
      {/* 🌟 מפל נצנצים וחלקיקי זהב זוהרים */} [cite: 301]
      <div [cite: 301]
        className="absolute inset-0 opacity-[0.25] pointer-events-none" [cite: 302]
        style={{ [cite: 302]
          backgroundImage: ` [cite: 302]
            radial-gradient(circle, #d4af37 1px, transparent 1px), [cite: 302]
            radial-gradient(circle, #f3e5ab 1.5px, transparent 1.5px), [cite: 302]
            radial-gradient(circle, #ffffff 1px, transparent 1px) [cite: 302]
          `, [cite: 302]
          backgroundSize: '30px 30px, 45px 45px, 20px 20px', [cite: 302]
          backgroundPosition: '0 0, 15px 20px, 5px 5px' [cite: 302]
        }} [cite: 302]
      ></div> [cite: 302]

      {/* הילות אור נוצצות */} [cite: 302]
      <div className="absolute top-[-10%] right-[5%] w-[800px] h-[500px] bg-gradient-to-br from-[#ffd700]/20 to-[#fff8dc]/40 rounded-full blur-[140px] pointer-events-none"></div> [cite: 302, 303]
      <div className="absolute top-[40%] left-[-10%] w-[600px] h-[600px] bg-[#fdf5e6]/50 rounded-full blur-[120px] pointer-events-none"></div> [cite: 303]

      {/* 🛍️ סרגל עליון מהיר */} [cite: 303]
      <nav className="relative z-30 max-w-7xl mx-auto px-6 pt-6 flex justify-between items-center"> [cite: 303]
        <div className="text-sm font-serif tracking-widest text-[#8b6508] font-bold">LUXE COUTURE</div> [cite: 303]
        <div className="flex gap-3 flex-wrap"> [cite: 303]
          <button [cite: 303]
            onClick={() => setIsAddDressOpen(true)} [cite: 304]
            className="px-4 py-2 bg-gradient-to-r from-[#d4af37] to-[#b8860b] hover:from-[#b8860b] hover:to-[#8b6508] text-white rounded-xl text-xs font-bold transition-all shadow-md flex items-center gap-1.5" [cite: 304]
          > [cite: 304]
            <span>➕</span> [cite: 304]
            <span>הוספת שמלה לאתר</span> [cite: 304]
          </button> [cite: 304]
          
          <button [cite: 305]
            onClick={() => setShowOnlyFavorites(!showOnlyFavorites)} [cite: 305]
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 border border-[#dfc48c] shadow-sm ${ [cite: 305]
              showOnlyFavorites ? [cite: 305]
                'bg-[#d4af37] text-white' : 'bg-white/90 text-[#8b6508]' [cite: 306]
            }`} [cite: 306]
          > [cite: 306]
            <span>❤️</span> [cite: 306]
            <span>מועדפים ({favorites.length})</span> [cite: 306]
          </button> [cite: 306]
          
          <button [cite: 306]
            onClick={() => setIsCartOpen(true)} [cite: 306]
            className="px-4 py-2 bg-[#2c261a] hover:bg-[#b8860b] text-white rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 shadow-md" [cite: 307]
          > [cite: 307]
            <span>🛍️</span> [cite: 307]
            <span>הסל שלי ({cart.length})</span> [cite: 307]
          </button> [cite: 307]
        </div> [cite: 307]
      </nav> [cite: 307]

      {/* 👑 לוגו וכותרת שטיח אדום */} [cite: 307]
      <header className="relative pt-14 pb-10 px-6 text-center z-10"> [cite: 308]
        <div className="inline-block animate-pulse mb-2"> [cite: 308]
          <span className="text-[11px] uppercase tracking-[0.4em] bg-gradient-to-r from-[#b8860b] via-[#d4af37] to-[#b8860b] bg-clip-text text-transparent font-black"> [cite: 308]
            ✦ HIGH GLAMOUR EXCLUSIVE ✦ [cite: 308]
          </span> [cite: 308]
        </div> [cite: 308]
        <h1 className="text-5xl font-black tracking-tight text-neutral-900 sm:text-6xl drop-shadow-[0_2px_10px_rgba(212,175,55,0.15)]"> [cite: 308]
          LUXE <span className="font-serif italic font-light bg-gradient-to-r from-[#8b6508] to-[#d4af37] bg-clip-text text-transparent">COUTURE</span> [cite: 308, 309]
        </h1> [cite: 309]
        <div className="flex items-center justify-center gap-3 mt-4 mb-4"> [cite: 309]
          <div className="w-16 h-[1px] bg-gradient-to-r from-transparent to-[#d4af37]"></div> [cite: 309]
          <span className="text-[#d4af37] text-xs">✦</span> [cite: 309]
          <div className="w-16 h-[1px] bg-gradient-to-l from-transparent to-[#d4af37]"></div> [cite: 309]
        </div> [cite: 309]
        <p className="text-sm text-[#554a33] max-w-lg mx-auto font-medium leading-relaxed"> [cite: 309]
          המראה הזוהר והנוצץ ביותר לאירוע הבא שלך. דפדפי בקולקציה, סמני מועדפים ושרייני בקליק את התאריך שלך. [cite: 309, 310]
        </p> [cite: 310]
      </header> [cite: 310]

      {/* 🔍 פאנל סינונים קריסטלי מבריק */} [cite: 311]
      <section className="max-w-6xl mx-auto px-4 mb-14 relative z-10"> [cite: 311]
        <div className="bg-white/90 backdrop-blur-xl p-6 rounded-2xl border-2 border-[#e6c687] shadow-[0_20px_50px_rgba(212,175,55,0.18)] grid grid-cols-1 md:grid-cols-3 gap-6 items-end"> [cite: 311]
          <div> [cite: 311]
            <label className="block text-xs font-black text-[#8b6508] tracking-wide mb-2">חפשי שמלה זוהרת</label> [cite: 311]
            <input  [cite: 311]
              type="text"  [cite: 312]
              placeholder="שמלת החלומות שלך..."  [cite: 312]
              value={searchTerm}  [cite: 312]
              onChange={(e) => setSearchTerm(e.target.value)}  [cite: 312]
              className="w-full p-3 bg-neutral-50/50 border border-[#dfc48c] rounded-xl text-xs text-neutral-900 font-medium focus:outline-none focus:border-[#d4af37] focus:ring-1 focus:ring-[#d4af37] transition placeholder-neutral-400"  [cite: 312]
            /> [cite: 312]
          </div> [cite: 312]

          <div> [cite: 313]
            <label className="block text-xs font-black text-[#8b6508] tracking-wide mb-2">בחרי מידה</label> [cite: 313]
            <div className="flex gap-1.5 bg-[#f5ebd2] p-1 rounded-xl border border-[#dec085]"> [cite: 313]
              {['All', 'S', 'M', 'L'].map((size) => ( [cite: 313]
                <button  [cite: 313]
                  key={size}  [cite: 314]
                  onClick={() => setSelectedSize(size)}  [cite: 314]
                  className={`flex-1 py-1.5 rounded-lg text-xs font-bold transition-all ${ [cite: 314]
                    selectedSize === size  [cite: 314]
                      ? 'bg-gradient-to-r from-[#d4af37] to-[#aa8010] text-white shadow-md transform scale-102 font-black'  [cite: 315]
                      : 'text-[#6d5b3a] hover:text-black hover:bg-white/40' [cite: 315]
                  }`} [cite: 315]
                > [cite: 315]
                  {size === 'All' ? 'הכל' : size} [cite: 315, 316]
                </button> [cite: 316]
              ))} [cite: 316]
            </div> [cite: 316]
          </div> [cite: 316]

          <div> [cite: 316]
            <div className="flex justify-between text-xs font-black text-[#8b6508] mb-2"> [cite: 316]
              <span>טווח תקציב</span> [cite: 316]
              <span className="text-black font-black bg-[#f5ebd2] px-2 py-0.5 rounded border border-[#dec085]">₪{maxPrice}</span> [cite: 317]
            </div> [cite: 317]
            <input  [cite: 317]
              type="range"  [cite: 317]
              min="300"  [cite: 317]
              max="1000"  [cite: 317]
              step="50"  [cite: 318]
              value={maxPrice}  [cite: 318]
              onChange={(e) => setMaxPrice(Number(e.target.value))}  [cite: 318]
              className="w-full accent-[#d4af37] h-1.5 bg-[#eadaaf] rounded-lg cursor-pointer"  [cite: 318]
            /> [cite: 318]
          </div> [cite: 318]
        </div> [cite: 318]
      </section> [cite: 318]

      {/* 👗 גלריית השמלות */} [cite: 319]
      <section className="max-w-6xl mx-auto px-4 relative z-10"> [cite: 319]
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8"> [cite: 319]
          {filteredDresses.map((dress) => { [cite: 319]
            const currentImgIndex = currentImageIndexes[dress.id] || 0; [cite: 319, 320]
            const isFav = favorites.includes(dress.id); [cite: 320]
            const inCart = cart.some(item => item.id === dress.id); [cite: 320]
            return ( [cite: 321]
              <div  [cite: 321]
                key={dress.id}  [cite: 321]
                className="group flex flex-col h-full bg-white rounded-2xl overflow-hidden border-2 border-[#ebd3a4]/60 shadow-[0_10px_30px_rgba(212,175,55,0.06)] hover:shadow-[0_25px_60px_rgba(212,175,55,0.22)] hover:border-[#d4af37] transition-all duration-300 transform hover:-translate-y-1" [cite: 321]
              > [cite: 321]
                {/* 📸 גלריית התמונות */} [cite: 321]
                <div className="h-[430px] w-full relative overflow-hidden bg-[#faf8f3] p-2.5"> [cite: 322]
                  <div className="w-full h-full rounded-xl overflow-hidden relative border border-[#f0e2c3]"> [cite: 322]
                    
                    <button  [cite: 322]
                      onClick={(e) => toggleFavorite(dress.id, e)} [cite: 323]
                      className="absolute top-3 left-3 z-10 bg-white/90 hover:bg-white w-8 h-8 rounded-full flex items-center justify-center shadow-md border border-[#eadaaf] text-sm transition transform active:scale-90" [cite: 323]
                    > [cite: 323]
                      {isFav ? '❤️' : '🤍'} [cite: 323, 324]
                    </button> [cite: 324]

                    <span className="absolute top-3 right-3 z-10 bg-gradient-to-r from-[#d4af37] to-[#b8860b] text-white text-[10px] font-black px-3 py-1 rounded shadow-md"> [cite: 324]
                      מידה {dress.size} [cite: 324]
                    </span> [cite: 324]

                    {/* חצים */} [cite: 325]
                    {dress.images.length > 1 && ( [cite: 325]
                      <> [cite: 325]
                        <button  [cite: 325]
                          onClick={(e) => prevImage(dress.id, dress.images.length, e)} [cite: 326]
                          className="absolute left-2.5 top-1/2 -translate-y-1/2 z-20 bg-white/95 text-[#b8860b] w-9 h-9 rounded-full flex items-center justify-center shadow-lg border border-[#e8cc92] font-black text-lg hover:bg-gradient-to-r hover:from-[#d4af37] hover:to-[#b8860b] hover:text-white transition-all opacity-0 group-hover:opacity-100" [cite: 326]
                        > [cite: 326]
                          ‹ [cite: 327]
                        </button> [cite: 327]
                        <button  [cite: 327]
                          onClick={(e) => nextImage(dress.id, dress.images.length, e)} [cite: 328]
                          className="absolute right-2.5 top-1/2 -translate-y-1/2 z-20 bg-white/95 text-[#b8860b] w-9 h-9 rounded-full flex items-center justify-center shadow-lg border border-[#e8cc92] font-black text-lg hover:bg-gradient-to-r hover:from-[#d4af37] hover:to-[#b8860b] hover:text-white transition-all opacity-0 group-hover:opacity-100" [cite: 328]
                        > [cite: 328]
                          › [cite: 329]
                        </button> [cite: 329]
                      </> [cite: 325]
                    )} [cite: 325]

                    <img src={dress.images[currentImgIndex]} alt={dress.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 ease-out" /> [cite: 329]

                    <div className="absolute bottom-3 left-1/2 -translate-x-1/2 z-20 flex gap-1 bg-white/95 px-2.5 py-1 rounded-full shadow-md border border-[#e0cba0]"> [cite: 330]
                      {dress.images.map((_, idx) => ( [cite: 330]
                        <div key={idx} className={`w-1.5 h-1.5 rounded-full transition-all duration-300 ${idx === currentImgIndex ? 'bg-[#d4af37] w-3.5' : 'bg-[#e5d9bd]'}`} /> [cite: 330, 331]
                      ))} [cite: 330]
                    </div> [cite: 330]
                  </div> [cite: 330]
                </div> [cite: 330]

                {/* פרטי השמלה והמחיר */} [cite: 332]
                <div className="p-5 flex flex-col flex-grow bg-gradient-to-b from-white to-[#fdfbf7]"> [cite: 332]
                  <div className="flex justify-between items-start gap-2"> [cite: 332]
                    <h3 className="text-lg font-bold text-neutral-900 tracking-wide group-hover:text-[#b8860b] transition-colors">{dress.name}</h3> [cite: 332]
                    <button  [cite: 332]
                      onClick={(e) => toggleCart(dress, e)} [cite: 333]
                      className={`text-xs p-1.5 rounded-lg border transition ${ [cite: 333]
                        inCart ? 'bg-[#f4ebd4] border-[#d4af37] text-[#b8860b]' : 'border-neutral-200 hover:bg-neutral-50' [cite: 334]
                      }`} [cite: 334]
                      title={inCart ? "הסר מהסל" : "הוסף לסל שריונות מרוכז"} [cite: 334, 335]
                    > [cite: 335]
                      {inCart ? '🛒 בסל' : '➕ לסל'} [cite: 336]
                    </button> [cite: 336]
                  </div> [cite: 336]
                  <p className="mt-1.5 text-xs text-[#6e634c] font-normal leading-relaxed line-clamp-2 flex-grow"> [cite: 336]
                    {dress.description} [cite: 336]
                  </p> [cite: 337]
                  
                  <div className="flex justify-between items-center mt-5 pt-4 border-t-2 border-dotted border-[#f0e6cc]"> [cite: 337]
                    <div className="flex flex-col"> [cite: 337]
                      <span className="text-[9px] uppercase tracking-widest text-[#b8860b] font-black">השכרה חגיגית</span> [cite: 337]
                      <span className="text-neutral-900 font-black text-lg">₪{dress.price}</span> [cite: 338]
                    </div> [cite: 338]
                    <button  [cite: 338]
                      onClick={() => { [cite: 338]
                        setSelectedDress(dress); [cite: 339]
                        setModalImageIndex(currentImgIndex); [cite: 339]
                      }}  [cite: 340]
                      className="bg-gradient-to-r from-[#2c261a] to-[#4a3f2b] hover:from-[#d4af37] hover:to-[#b8860b] text-white text-xs font-bold px-4 py-3 rounded-xl transition-all duration-300 shadow-md hover:shadow-lg transform active:scale-98" [cite: 340]
                    > [cite: 340]
                      שרייני לערב הזוהר שלך [cite: 340]
                    </button> [cite: 340]
                  </div> [cite: 340]
                </div> [cite: 340]
              </div> [cite: 341]
            ); [cite: 341]
          })} [cite: 342]
        </div> [cite: 342]
      </section> [cite: 342]

      {/* ✨ מודאל הוספת שמלה לאתר ✨ */} [cite: 342]
      {isAddDressOpen && ( [cite: 342]
        <div className="fixed inset-0 bg-neutral-900/60 backdrop-blur-md z-50 flex items-center justify-center p-4 overflow-y-auto"> [cite: 342]
          <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-2xl relative border-2 border-[#d4af37] max-h-[90vh] overflow-y-auto" style={{ direction: 'rtl' }}> [cite: 342]
            <button  [cite: 342]
              onClick={() => setIsAddDressOpen(false)}  [cite: 343]
              className="absolute top-4 left-4 bg-neutral-100 hover:bg-[#d4af37] text-[#b8860b] hover:text-white w-8 h-8 rounded-full flex items-center justify-center border shadow-sm font-bold transition-all" [cite: 343]
            > [cite: 343]
              ✕ [cite: 343]
            </button> [cite: 343]

            <div className="text-center mb-5"> [cite: 343]
              <span className="text-[10px] uppercase tracking-[0.2em] text-[#b8860b] font-black block mb-1">✦ ADD TO THE COLLECTION ✦</span> [cite: 344]
              <h3 className="text-xl font-black text-neutral-950">הוספת דגם שמלה חדש</h3> [cite: 344]
              <div className="w-12 h-[1px] bg-[#d4af37] mx-auto mt-2"></div> [cite: 344]
            </div> [cite: 344]

            <form onSubmit={handleAddDressSubmit} className="flex flex-col gap-4"> [cite: 344]
              <div> [cite: 344]
                <label className="block text-xs font-bold text-[#8b6508] mb-1">שם הדגם / השמלה *</label> [cite: 345]
                <input  [cite: 345]
                  type="text"  [cite: 345]
                  required  [cite: 345]
                  placeholder="למשל: שמלת משי פנינה" [cite: 346]
                  value={newDressData.name}  [cite: 346]
                  onChange={(e) => setNewDressData({...newDressData, name: e.target.value})}  [cite: 346]
                  className="w-full p-2.5 bg-neutral-50 border border-[#decfa8] rounded-xl text-xs font-medium focus:outline-none focus:border-[#d4af37]"  [cite: 346]
                /> [cite: 347]
              </div> [cite: 347]

              <div className="grid grid-cols-2 gap-4"> [cite: 347]
                <div> [cite: 347]
                  <label className="block text-xs font-bold text-[#8b6508] mb-1">מחיר השכרה (₪) *</label> [cite: 347]
                  <input  [cite: 348]
                    type="number"  [cite: 348]
                    required  [cite: 348]
                    placeholder="350" [cite: 348]
                    value={newDressData.price}  [cite: 348]
                    onChange={(e) => setNewDressData({...newDressData, price: e.target.value})}  [cite: 349]
                    className="w-full p-2.5 bg-neutral-50 border border-[#decfa8] rounded-xl text-xs font-medium focus:outline-none focus:border-[#d4af37]"  [cite: 349]
                  /> [cite: 349]
                </div> [cite: 349]

                <div> [cite: 350]
                  <label className="block text-xs font-bold text-[#8b6508] mb-1">מידה *</label> [cite: 350]
                  <select  [cite: 350]
                    required [cite: 350]
                    value={newDressData.size} [cite: 351]
                    onChange={(e) => setNewDressData({...newDressData, size: e.target.value})} [cite: 351]
                    className="w-full p-2.5 bg-neutral-50 border border-[#decfa8] rounded-xl text-xs font-medium focus:outline-none focus:border-[#d4af37]" [cite: 351]
                  > [cite: 351]
                    <option value="">בחרי...</option> [cite: 351]
                    <option value="XS">XS (34)</option> [cite: 352]
                    <option value="S">S (36)</option> [cite: 352]
                    <option value="M">M (38)</option> [cite: 352]
                    <option value="L">L (40)</option> [cite: 352]
                    <option value="XL">XL (42)</option> [cite: 353]
                  </select> [cite: 351]
                </div> [cite: 351]
              </div> [cite: 353]

              <div> [cite: 353]
                <label className="block text-xs font-bold text-[#8b6508] mb-1">צבע השמלה</label> [cite: 354]
                <input  [cite: 354]
                  type="text"  [cite: 354]
                  placeholder="למשל: לבן שמנת, ורוד עתיק" [cite: 354]
                  value={newDressData.color}  [cite: 354]
                  onChange={(e) => setNewDressData({...newDressData, color: e.target.value})}  [cite: 355]
                  className="w-full p-2.5 bg-neutral-50 border border-[#decfa8] rounded-xl text-xs font-medium focus:outline-none focus:border-[#d4af37]"  [cite: 355]
                /> [cite: 355]
              </div> [cite: 355]

              <div> [cite: 355]
                <label className="block text-xs font-bold text-[#8b6508] mb-2">מצב השמלה</label> [cite: 356]
                <div className="flex gap-4 bg-neutral-50 p-2.5 rounded-xl border border-[#decfa8] justify-around"> [cite: 356]
                  <label className="flex items-center gap-1.5 text-xs font-medium cursor-pointer"> [cite: 356]
                    <input  [cite: 356]
                      type="radio"  [cite: 357]
                      name="condition"  [cite: 357]
                      value="new" [cite: 357]
                      checked={newDressData.condition === 'new'} [cite: 357]
                      onChange={(e) => setNewDressData({...newDressData, condition: e.target.value})} [cite: 358]
                      className="accent-[#d4af37]" [cite: 358]
                    /> [cite: 358]
                    חדש עם תווית [cite: 358]
                  </label> [cite: 358]
                  <label className="flex items-center gap-1.5 text-xs font-medium cursor-pointer"> [cite: 359]
                    <input  [cite: 359]
                      type="radio"  [cite: 359]
                      name="condition"  [cite: 359]
                      value="like-new" [cite: 359]
                      checked={newDressData.condition === 'like-new'} [cite: 359]
                      onChange={(e) => setNewDressData({...newDressData, condition: e.target.value})} [cite: 359]
                      className="accent-[#d4af37]" [cite: 359]
                    /> [cite: 359]
                    כמו חדש [cite: 359]
                  </label> [cite: 359]
                  <label className="flex items-center gap-1.5 text-xs font-medium cursor-pointer"> [cite: 359]
                    <input  [cite: 359]
                      type="radio"  [cite: 359]
                      name="condition"  [cite: 359]
                      value="used" [cite: 359]
                      checked={newDressData.condition === 'used'} [cite: 359]
                      onChange={(e) => setNewDressData({...newDressData, condition: e.target.value})} [cite: 359]
                      className="accent-[#d4af37]" [cite: 359]
                    /> [cite: 359]
                    יד שנייה [cite: 359]
                  </label> [cite: 359]
                </div> [cite: 356]
              </div> [cite: 356]

              <div> [cite: 359]
                <label className="block text-xs font-bold text-[#8b6508] mb-1">תיאור השמלה וסוג הבד</label> [cite: 359]
                <textarea  [cite: 359]
                  rows={3}  [cite: 359]
                  placeholder="ספרי על השמלה, סוג הבד, התאמה לאירועים..."  [cite: 359]
                  value={newDressData.description}  [cite: 359]
                  onChange={(e) => setNewDressData({...newDressData, description: e.target.value})}  [cite: 359]
                  className="w-full p-2.5 bg-neutral-50 border border-[#decfa8] rounded-xl text-xs font-medium focus:outline-none focus:border-[#d4af37] resize-none"  [cite: 359]
                /> [cite: 359]
              </div> [cite: 359]

              <div> [cite: 359]
                <label className="block text-xs font-bold text-[#8b6508] mb-1">העלאת תמונות של השמלה</label> [cite: 359]
                <input  [cite: 359]
                  type="file"  [cite: 359]
                  multiple  [cite: 359]
                  accept="image/*"  [cite: 359]
                  onChange={handleImageUpload}  [cite: 359]
                  className="w-full p-2 bg-neutral-50 border border-dashed border-[#decfa8] rounded-xl text-xs file:ml-4 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-bold file:bg-[#f4ebd4] file:text-[#8b6508] hover:file:bg-[#eadaaf] cursor-pointer"  [cite: 359]
                /> [cite: 359]
                {newDressData.images.length > 0 && ( [cite: 359]
                  <div className="flex gap-2 flex-wrap mt-2 bg-neutral-50 p-2 rounded-xl border border-neutral-100"> [cite: 359]
                    {newDressData.images.map((img, index) => ( [cite: 359]
                      <img key={index} src={img} alt="תצוגה מקדימה" className="w-12 h-12 object-cover rounded-lg border border-[#decfa8]" /> [cite: 359]
                    ))} [cite: 359]
                  </div> [cite: 359]
                )} [cite: 359]
              </div> [cite: 359]

              <button type="submit" className="w-full bg-gradient-to-r from-[#d4af37] via-[#b8860b] to-[#d4af37] hover:from-[#b8860b] hover:to-[#8b6508] text-white text-xs font-black py-3.5 rounded-xl shadow-lg mt-2 transition-transform active:scale-98"> [cite: 359]
                פרסמי שמלה בקולקציה ✨ [cite: 359]
              </button> [cite: 359]
            </form> [cite: 359]
          </div> [cite: 359]
        </div> [cite: 359]
      )} [cite: 359]

      {/* 💬 סקשן חוות דעת לקוחות */} [cite: 359]
      <section className="max-w-6xl mx-auto px-4 mt-24 relative z-10"> [cite: 359]
        <div className="text-center mb-10"> [cite: 359]
          <span className="text-xs uppercase font-black text-[#b8860b] tracking-widest">REAL GLAMOUR STORIES</span> [cite: 359]
          <h2 className="text-3xl font-serif italic text-neutral-900 mt-1">מה הלקוחות שלנו מספרות</h2> [cite: 359]
          <div className="w-12 h-[1.5px] bg-[#d4af37] mx-auto mt-3"></div> [cite: 359]
        </div> [cite: 359]

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6"> [cite: 359]
          {REVIEWS.map((rev, index) => ( [cite: 359]
            <div key={index} className="bg-white/80 backdrop-blur-md p-6 rounded-2xl border border-[#eadaaf] shadow-sm flex flex-col justify-between"> [cite: 359]
              <div> [cite: 359]
                <div className="flex text-[#d4af37] gap-0.5 mb-3"> [cite: 359]
                  {Array.from({ length: rev.stars }).map((_, i) => <span key={i}>⭐</span>)} [cite: 359]
                </div> [cite: 359]
                <p className="text-xs text-[#554a33] italic leading-relaxed">"{rev.text}"</p> [cite: 359]
              </div> [cite: 359]
              <div className="mt-4 pt-3 border-t border-neutral-100 flex justify-between items-center"> [cite: 359]
                <span className="text-xs font-bold text-neutral-900">{rev.name}</span> [cite: 359]
                <span className="text-[10px] bg-[#f4ebd4] text-[#8b6508] px-2 py-0.5 rounded-full font-bold">{rev.role}</span> [cite: 359]
              </div> [cite: 359]
            </div> [cite: 359]
          ))} [cite: 359]
        </div> [cite: 359]
      </section> [cite: 359]

      {/* 👑 אזור שאלות נפוצות */} [cite: 359]
      <section className="max-w-3xl mx-auto px-4 mt-24 relative z-10"> [cite: 359]
        <div className="text-center mb-10"> [cite: 359]
          <h2 className="text-3xl font-serif italic text-neutral-900">שאלות ותשובות נפוצות</h2> [cite: 359]
          <div className="w-12 h-[1.5px] bg-[#d4af37] mx-auto mt-3"></div> [cite: 359]
        </div> [cite: 359]

        <div className="flex flex-col gap-3"> [cite: 359]
          {FAQS.map((faq, idx) => { [cite: 359]
            const isOpen = activeFaq === idx; [cite: 359]
            return ( [cite: 359]
              <div key={idx} className="bg-white border border-[#ebd4a8] rounded-xl overflow-hidden shadow-sm transition-all"> [cite: 359]
                <button [cite: 359]
                  onClick={() => setActiveFaq(isOpen ? null : idx)} [cite: 359]
                  className="w-full p-4 text-right flex justify-between items-center font-bold text-xs text-neutral-900 hover:bg-neutral-50 transition" [cite: 359]
                > [cite: 359]
                  <span>{faq.q}</span> [cite: 359]
                  <span className="text-[#b8860b] text-base">{isOpen ? '−' : '＋'}</span> [cite: 359]
                </button> [cite: 359]
                {isOpen && ( [cite: 359]
                  <div className="p-4 bg-[#fffdf9] border-t border-[#f7eed8] text-xs text-[#5c5037] leading-relaxed"> [cite: 359]
                    {faq.a} [cite: 359]
                  </div> [cite: 359]
                )} [cite: 359]
              </div> [cite: 359]
            ); [cite: 359]
          })} [cite: 359]
        </div> [cite: 359]
      </section> [cite: 359]

      {/* 🛒 מודאל מגירה צידית - סל השריונות */} [cite: 359]
      {isCartOpen && ( [cite: 359]
        <div className="fixed inset-0 bg-neutral-900/50 backdrop-blur-sm z-50 flex justify-end"> [cite: 359]
          <div className="bg-white w-full max-w-md h-full p-6 shadow-2xl flex flex-col justify-between border-r-2 border-[#d4af37]"> [cite: 359]
            <div> [cite: 359]
              <div className="flex justify-between items-center pb-4 border-b border-neutral-200"> [cite: 359]
                <h3 className="text-lg font-bold text-neutral-900">סל השריונות שלך 🛒</h3> [cite: 359]
                <button onClick={() => setIsCartOpen(false)} className="text-neutral-400 hover:text-black font-bold text-lg">✕</button> [cite: 359]
              </div> [cite: 359]

              {cart.length === 0 ? ( [cite: 359]
                <p className="text-xs text-[#6e634c] text-center py-12">הסל שלך עדיין ריק. הוסיפי שמלות כדי לבצע הזמנה מרוכזת.</p> [cite: 359]
              ) : ( [cite: 359]
                <div className="flex flex-col gap-4 mt-4 overflow-y-auto max-h-[60vh] p-1"> [cite: 359]
                  {cart.map(item => ( [cite: 359]
                    <div key={item.id} className="flex gap-3 items-center bg-gradient-to-r from-neutral-50 to-[#fffdf9] p-2 rounded-xl border border-[#ebd4a8]"> [cite: 359]
                      <img src={item.images[0]} alt={item.name} className="w-16 h-16 object-cover rounded-lg border" /> [cite: 359]
                      <div className="flex-grow"> [cite: 359]
                        <h4 className="text-xs font-bold text-neutral-950">{item.name}</h4> [cite: 359]
                        <span className="text-[10px] text-[#b8860b] block">מידה {item.size}</span> [cite: 359]
                        <span className="text-xs font-black text-neutral-900">₪{item.price}</span> [cite: 359]
                      </div> [cite: 359]
                    </div> [cite: 359]
                  ))} [cite: 359]
                </div> [cite: 359]
              )} [cite: 359]
            </div> [cite: 359]
          </div> [cite: 359]
        </div> [cite: 359]
      )} [cite: 359]

    </main> [cite: 359]
  ); [cite: 359]
}
